### ISSUE TITLE
Conversion ratio for US dry quart and US dry pint incorrect

### ISSUE THREAD

**Issue by kevinwhkim** [jonahsnider/convert#317]
When doing conversions with US dry quart and US dry pint to litres the values are incorrect (i.e. `convert(1, 'US dry quart').to('l')`)

The correct ratio values for dry measures are listed here (https://en.wikipedia.org/wiki/United_States_customary_units#Dry_volume and https://en.wikipedia.org/wiki/Dry_measure#US_units_of_dry_measure) as mentioned in the comments in `src/dev/conversions/volume.ts`.

Expected behaviour:
`1 US dry quart = 1.101221 L`
`1 US dry pint = 0.550610 L`

Actual behaviour:
`1 US dry quart = 0.946352946 L`
`1 US dry pint = 33600.3125 L`

**Comment by jonahsnider** [comment]
Sorry about that, looks like some of the conversion ratios I had entered in were in cubic inches instead of cubic meters. Should be fixed in the next release.
