### ISSUE TITLE
Adding pixels, point to length type

### ISSUE THREAD

**Issue by huffmanks** [jonahsnider/convert#535]
First off want to say love this package. Very clean and easy to use.

Feature request:
Thoughts on adding pixels and points to the length type?

**Comment by jonahsnider** [comment]
Pixels don't have a constant length, it depends on the pixel density of the screen.
Points and [picas](https://en.wikipedia.org/wiki/Pica_(typography)) can be added though, since they are always 1/72in and 1/6in, respectively.
