### ISSUE TITLE
Using convert with vanilla JS doesn't work

### ISSUE THREAD

**Issue by nikushx** [jonahsnider/convert#560]
I tried the **unpkg** link for this repo and it did not work. I hacked the script to extract the convert, convertMany, and ms functions out (if you're looking to do this just set `e` to an external variable where e.convert is being set.)

Maybe I did something wrong but I had to hack it to extract the convert function at all. It doesn't set on the window.

**Comment by jonahsnider** [comment]
Thanks for reporting this, the issue was a misconfiguration of Babel during the build process, which was causing the global variable used to be `unknown` instead of `convert`.

**Comment by mahony0** [comment]
This issue still persists as of v4.13.2. It shows "Uncaught TypeError: convert is not a function" error

**Comment by mahony0** [comment]
Here are further details,

convert looks like an object, not a method
![1](https://github.com/jonahsnider/convert/assets/2674488/e546c74e-5a21-40a1-802a-fff70456b038)

I can use like this
![2](https://github.com/jonahsnider/convert/assets/2674488/2eeeba9f-125e-460b-a1c3-934d88d11961)

**Comment by jonahsnider** [comment]
Please see #612
