### ISSUE TITLE
Meters to kilometers and rounding

### ISSUE THREAD

**Issue by radzk** [jonahsnider/convert#563]
Hi, I couldn't find any information about doing a round operation automatically or even triggering it with some param.

So while the examples in readme seems to be accurate, the example of `convert(1930536, 'meters').to('best').toString()` returns me an ugly result of `1930.5359999999998km`. I expected to maybe get `1930.54km` as a result when using a "best" param.

**Comment by jonahsnider** [comment]
This is now supported by passing the number of digits to include to `.toString()`:
```js
convert(1930536, 'meters').to('best').toString(2); // '1930.54km'
```
