### ISSUE TITLE
Cannot get KB, MB, etc. units when using "best" for data conversion

### ISSUE THREAD

**Issue by agneslazo** [jonahsnider/convert#588]
When using the `"best"` parameter for data conversion it always returns the binary unit (KiB, MiB, etc.) for both the `"imperial"` or `"metric"` parameter. I think when using the "metric" param, it should be returning MB, GB, etc.

This seems to be a simple change in your `bestUnits` type for the `"metric"` kind, was hoping this could be updated.

Thanks!

**Comment by mrblue6ix** [comment]
I am also having a similar issue actually.
I need to convert seconds to the best unit possible, often these units will be ps, fs, or possibly smaller units. But for some reason, it seems the units defined for best for time only goes up to nano seconds (ns). 

Maybe I am missing something, but could this not be a pretty easy fix. Hoping this can possibly get updated
