### ISSUE TITLE
Typings can't be found on TypeScript 5

### ISSUE THREAD

**Issue by cyruseuros** [jonahsnider/convert#598]
[d.ts files cannot define types for .mjs files](https://stackoverflow.com/questions/72457791/typescript-packages-that-ship-with-mjs-and-d-ts-but-without-d-mts-how-to-i)

**Comment by jonahsnider** [comment]
Thanks so much for reporting this and providing a fix!

**Comment by cyruseuros** [comment]
Thanks for the quick patch!
