### ISSUE TITLE
Precision error during floating-point conversion

### ISSUE THREAD

**Issue by goodwin64** [jonahsnider/convert#645]
Heyyya, thanks for creating this library!

It looks like it repeats the well-known Javascript precision error with `0.1 + 0.2 !== 0.3`.  

Repro:
https://codepen.io/goodwin64/pen/vYPrMRW?editors=1010

**Comment by jonahsnider** [comment]
Floating point numbers aren't a bug. ECMAScript implements IEEE 754 exactly as the spec describes.
https://262.ecma-international.org/14.0/#sec-mathematical-operations

**Comment by goodwin64** [comment]
Just to clarify - [here's how](https://runkit.com/embed/njmaql9snx7j) `convert-units` performs the same unit and value conversion:
```ts
var convertUnits = require("convert-units")
console.log('>>> 77_600 g to kg:', convertUnits(77600).from('g').to('kg'))
​
# ">>> 77_600 g to kg:"
# 77.6
```
