### ISSUE TITLE
How to Use this library with Ember

### ISSUE THREAD

**Issue by maheshheda14** [jonahsnider/convert#651]
I have tried to install and trying to import but it is giving me error like ' Could not find module `convert` imported from'.  Though I am able to see this in node_modules. Please suggest me how to procceed.

Version used: 5.0.0

**Comment by jonahsnider** [comment]
I just created an Ember app to test and had no issues running Convert in a route:

![Ember app screenshot](https://github.com/jonahsnider/convert/assets/7608555/d9fb25e6-a5e1-460c-93b7-160d1fc324e9)

![Route](https://github.com/jonahsnider/convert/assets/7608555/c54edd33-1888-4511-9f25-4f91418ec3d4)

![Template](https://github.com/jonahsnider/convert/assets/7608555/70b90861-22cb-4667-a531-ab35565dcab4)
