### ISSUE TITLE
use 'm' for minutes

### ISSUE THREAD

**Issue by itzTheMeow** [jonahsnider/convert#659]
Is there a way to use `m` for minutes with the ms shorthand utility? I see `m` is used for meters currently but its also commonly used for minutes. (even in the ms package)

**Comment by jonahsnider** [comment]
It might be possible to add in special behavior when it seems like you're converting time (or using `ms()`) but use the unit `m`. I'll play around with some ideas and update here if I get something working.

**Comment by itzTheMeow** [comment]
much appreciated!
