### ISSUE TITLE
Bug in `.to('best', 'imperial')`

### ISSUE THREAD

**Issue by kai-dorschner-twinsity** [jonahsnider/convert#709]
I wrote a test to verify it converts back and forth to the best fitting unit (essentially an identity conversion):

```js
  it('checks out', () => {
    expect(convert(convert(1, 'sq mi').to('m2'), 'm2').to('sq mi')).toBe(1); // ✔️ explicit conversion works as expected
    expect(convert(convert(1, 'sq mi').to('m2'), 'm2').to('best', 'imperial')).toMatchObject({
      quantity: 1,
      unit: 'sq mi',
    }); // ❌ implicit conversion doesn't work, see screenshot
  });
```
Result:
![image](https://github.com/user-attachments/assets/b671daf8-f1c5-4759-8b7a-9f2c32cccab0)

I expect it to convert to the next highest unit when its value is `>= 1` but it stays at acres (indefinitely). Even when going up to 10 or 100 square miles it is not working, see:
![image](https://github.com/user-attachments/assets/b8924932-1a93-4a26-bafa-d2b9387f43c4)

I think the same problem applies between square feet <-> acres. If you're interested I can produce a test for that as well.

For metric system everything works as expected.

**Comment by jonahsnider** [comment]
This issue doesn't have to do with converting back and forth. It's just that the array of imperial units to use for area lists acres as being larger than square miles, hence `640 ac` being returned instead of `1 sq mi`.
